version: 2
updates:
  - commit-message:
      prefix: "chore"
    directory: /
    package-ecosystem: pip
    schedule:
      interval: weekly
  - commit-message:
      prefix: "chore"
    directory: /tests/unit/
    package-ecosystem: pip
    schedule:
      interval: weekly
